dummy:

install:
	mkdir -p ${DESTDIR}/home/z/share/make_cfg/
	install -m644 make.defs ${DESTDIR}/home/z/share/make_cfg/make.defs
	install -m644 make.rules ${DESTDIR}/home/z/share/make_cfg/make.rules
	install -m644 Makefile.tmpl ${DESTDIR}/home/z/share/make_cfg/Makefile.tmpl
