dummy:


install:
	mkdir -p ${DESTDIR}/home/y/share/make_cfg/
	install -m644 make.defs ${DESTDIR}/home/y/share/make_cfg/make.defs
	install -m644 make.rules ${DESTDIR}/home/y/share/make_cfg/make.rules
	install -m644 Makefile.tmpl ${DESTDIR}/home/y/share/make_cfg/Makefile.tmpl
#	mkdir -p ${DESTDIR}/usr/share/make_cfg/
#	install -m644 make.defs ${DESTDIR}/usr/share/make_cfg/make.defs
#	install -m644 make.rules ${DESTDIR}/usr/share/make_cfg/make.rules
#	install -m644 Makefile.tmpl ${DESTDIR}/usr/share/make_cfg/Makefile.tmpl
#	mkdir -p ${DESTDIR}/usr/local/share/make_cfg/
#	install -m644 make.defs ${DESTDIR}/usr/local/share/make_cfg/make.defs
#	install -m644 make.rules ${DESTDIR}/usr/local/share/make_cfg/make.rules
#	install -m644 Makefile.tmpl ${DESTDIR}/usr/local/share/make_cfg/Makefile.tmpl
